### PR TITLE
Fix several issues with column type guessing and header names

### PR DESCRIPTION
**Pull request by robertknight**
* Ignore NULL values when guessing column types

 * Fix error when guessing column types in CSV files that had fewer
   than 3 rows due to the input file seek position not being reset
   before reading the file to guess the column types

 * Replace delimiter detection function with the csv library's
   built-in sniffer

 * Strip whitespace around header column names

 * Switch tests to pyunit and add tests for column type guessing

### CODE REVIEW

**Comment by robertknight** [comment]
Yes, I've changed the table name parameter back to being an optional positional argument as it was before.

**Comment by rgrp** [comment]
Great. Note I'm also really happy to have the --table option (it is definitely better) and then we can deprecate the positional arg (it is just we should do that over a bit of time).

**Comment by rgrp** [comment]
Thanks a lot for the excellent update! I should quickly confirm you are happy with licensing under the public domain license. If you would like an author credit please just add a PR for the README.

**Comment by robertknight** [comment]
Yes, public domain is fine with me

**Pull request merged**
