### PR TITLE
fixing except syntax

### PR DESCRIPTION
**Pull request by sboysel**
Fixes `SyntaxError` in row processing
```python
  File "/home/sam/repos/thesis/code/utils/csv2sqlite.py", line 93
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

### CODE REVIEW

**Comment by rgrp** [comment]
Are you running python 3 or python 2.X - could you test with both by any chance?

**Comment by sboysel** [comment]
I've tested 5844e24 with both python 2.7.11 and 3.5.1 and everything seems to function properly with the following test csv
```
a,b,c,d
1,2,3.0,"e"
4,5,6.0,"f"
7,8,9.0,"g"
```

**Comment by rgrp** [comment]
@sboysel that's brilliant - one last thing could you also add a test that triggers whatever was the brokenness before (and is, I assume, now passing). Thank-you so much for helping improving the library!

**Comment by sboysel** [comment]
The error seems to come from general incompatibility with python 3.  On the master branch, one could reproduce with
```
[sam@malko csv2sqlite 05:50:45]$ python --version
Python 3.5.1
[sam@malko csv2sqlite 05:50:53]$ python csv2sqlite.py test.csv test.db
  File "csv2sqlite.py", line 93
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```
The fixes in sboysel@c6e3b231821d1f229891cccc0f63a7a23b3a9797 pass the provided tests for both 2 and 3.  Let me know if you'd like any other additional changes.  Thank you for the script!

**Comment by rgrp** [comment]
Got you! thanks. I will merge.

BTW: I assume you are happy with the public domain license?

**Comment by sboysel** [comment]
@rgrp Very happy.  Thank you.

**Pull request merged**
