### PR TITLE
Allow headers to be read from a separate file.

### PR DESCRIPTION
**Pull request by musically-ut**
This is to help in cases when the original (large) csv file doesn't contain a header line and it is undesirable to create a copy of the whole dataset just to add a header line.

A test case is included.

### CODE REVIEW

**Comment by rgrp** [comment]
Thanks for the additional feature. Just a few comments on styling ...

**Comment by rgrp** [comment]
Actually i think we merge and i can then make the tweaks necessary. Really appreciate and assume you are happy to make available under the Public Domain license in the README (please say if not!)

**Comment by musically-ut** [comment]
Yes, I have no issues with the Public Domain license.

I am curious to know what tweaks you suggest. :)

**Comment by rgrp** [comment]
@musically-ut :-) and thank-you for the contribution - this is what makes open-source fun! In terms of tweaks check ouf the latest commit.

**Pull request merged**
