### PR TITLE
Allow the input csv file to be compressed (bz2 or gzip)

### PR DESCRIPTION
**Pull request by musically-ut**
Additionally, these modules are present in the [python standard library](https://docs.python.org/2/library/archiving.html).

### CODE REVIEW

**Comment by rgrp** [comment]
Nice - could we get a unit test by any chance?

**Comment by musically-ut** [comment]
It would be tricky with the current unit test infrastructure (since they pass a fileobj instead of a file name). However, I should be able to cook something up with a temp file.

Will update this PR branch with the tests soon.

**Comment by musically-ut** [comment]
I have added some simple tests for compressed files.

**Comment by rgrp** [comment]
Great. Thank-you and merging now. I assume you are still happy with the license ;-)

Also I was wondering why no support for simple zip files (or am i misunderstanding bzip support)?

**Comment by musically-ut** [comment]
`bz2` and `gzip` are used to compress a single file. However, zip/tar **archives** may contain more than one file. It is complicated to reason which of those files one is supposed to pick and read. 

We can add support for zip (and/or tar) archives which have a single (csv) file inside them and throwing an error otherwise but then perhaps it is worth investing more time and allowing the user to pick a single file from inside an archive if we are going that far.

As a sidenote, I considered adding `7z` single-file compression support, but since it is not a part of the standard library, it would introduce dependencies into this otherwise clean standalone script.

**Comment by musically-ut** [comment]
Any updates or comments? :)

**Comment by rgrp** [comment]
@musically-ut thanks for the reminder and the contribution - i had meant to merge when i last commented.

Re zip: i think it would be worth trying something where you just take the first file with csv extension (or first file if only one file) in the zip.

**Pull request merged**
