### PR TITLE
Open file object with 'rU' & detects filename

### PR DESCRIPTION
**Pull request by nettolt**
fo = open(filepath_or_fileobj, 'rU')

### CODE REVIEW

**Comment by joshes** [comment]
Was about to send a PR for this very thing. Had to make the same change locally to intake some data.

**Comment by rgrp** [comment]
@joshes could you submit a PR for this as this existing one cannot be merged directly due to commits since.

**Comment by joshes** [comment]
Sent the PR. I only included the "open with rU" as I did not require the table name detection.
https://github.com/rgrp/csv2sqlite/pull/10

Thanks!

**Comment by rgrp** [comment]
@joshes thanks

@nettolt the file name detection is sort of nice so happy to have it - though we'd need to be a bit careful (e.g. to make sure the table name was a valid table name etc)

**Comment by rgrp** [comment]
I'm closing this pull request but happy to get a new one for table name stuff.

**Comment by joshes** [comment]
Cool, will add the table stuff as well, will send a PR for that soon.

**Pull request closed without merging**
